image: node:12.16.3
stages:
  - build
  - test
  - deploy

before_script:
  - npm install

cache:
    paths:
    - ./node_modules

build:
  script:
    - npm run build:gitlab
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
  - mv dist public
  - cp public/index.html public/404.html
  artifacts:
    paths:
    - public
  only:
  - master